<script lang="ts">
	import '../app.css';
	import discord from '$lib/assets/socials/discord-logo-blue.png';
	import github from '$lib/assets/socials/icone-github-jaune.png';
	import logo from '$lib/assets/logo-removebg.png';
	import Disclaimer from '$lib/components/Disclaimer.svelte';
	import { goto } from '$app/navigation';

	let disclaimerOpen = $state(false);
</script>

<main class="container mx-auto p-6">
	<img src={logo} alt="Infinite Tales Logo" class="m-auto mt-3 sm:w-1/4" />
	<section class="my-8 text-center">
		<h2 class="mb-4 text-2xl font-semibold">Shape Your Unique Tale</h2>
		<p class="mb-4">
			Infinite Tales RPG is a Choose Your Own Adventure Text RPG, dynamically narrated by AI.
		</p>
		<p class="mb-2">
			Customize every aspect of your adventure. Build your hero, explore vast lands, and make
			crucial decisions that determine your fate. Each adventure is uniquely generated by
			roleplaying AI, ensuring that no two journeys are alike. Your choices carve out a tale that is
			truly your own, offering infinite replayability.
		</p>
		<p class="mb-4">
			Let your custom Pen and Paper adventure in any game system like Dungeons and Dragons be guided
			by the AI Game Master.
		</p>
		<ul class="inline-block list-disc pl-5 text-left">
			<li><strong>Features currently in development</strong></li>
			<li><strong>Character Stats:</strong> Define your hero's strengths and weaknesses.</li>
			<li><strong>Dice Rolls:</strong> Experience the thrill of chance and strategy.</li>
			<li>
				<strong>Skills and Abilities:</strong> Develop unique abilities tailored to your playstyle.
			</li>
			<li>
				<strong>Character Progression:</strong> Grow and evolve your character throughout the story.
			</li>
			<li>
				<strong>Combat System:</strong> Engage in dynamic battles that test your tactics and wit.
			</li>
		</ul>
	</section>

	<section class="my-8 rounded-lg bg-gray-800 p-6 text-center shadow-md">
		<h2 class="mb-4 text-2xl font-semibold">How to Start Playing</h2>
		<p class="mb-4">
			To begin your tale, you need a Google Gemini API Key. It's free and easy to set up! View the <a
				target="_blank"
				href="https://github.com/JayJayBinks/infinite-tales-rpg/wiki/Create-your-free-Google-Gemini-API-Key-%F0%9F%94%91"
				class="text-blue-400 underline">guide to create the API Key</a
			>
		</p>
		<p>Your key is only stored in your browser, ensuring your privacy.</p>
	</section>

	<section class="my-8 text-center">
		<h2 class="mb-4 text-2xl font-semibold">Join the Beta</h2>
		<p class="mb-4">Experience the game in the early stages and help shape it's future.</p>
		<button class="btn btn-primary" onclick={() => (disclaimerOpen = true)}>Start Your Tale</button>
	</section>

	<section class="my-8 rounded-lg bg-gray-800 p-6 text-center shadow-md">
		<h2 class="mb-4 text-2xl font-semibold">Contact</h2>
		<a
			target="_blank"
			href="https://discord.gg/CUvgRQR77y"
			class="link m-auto mt-10 flex flex-col items-center"
		>
			<span>Community Discussion at Discord</span>
			<img class="m-auto mt-3 w-2/3 sm:w-1/5" src={discord} alt="Discord invite" />
		</a>
		<a
			target="_blank"
			class="link m-auto mt-10 flex flex-col items-center"
			href="https://github.com/JayJayBinks/infinite-tales-rpg"
		>
			<span>Source Code at Github</span>
			<img class="m-auto mt-3 w-1/3 sm:w-1/12" src={github} alt="Github Logo" />
		</a>
	</section>
	<section class="my-8 text-center">
		<h2 class="mb-4 text-2xl font-semibold">Open Source</h2>
		<p class="mb-4">
			Infinite Tales RPG is an open-source project, licensed under the GNU AGPLv3 License.
		</p>
	</section>
	<section class="my-8 rounded-lg bg-gray-800 p-6 text-center shadow-md">
		<h2 class="mb-2 text-2xl font-semibold">Acknowledgements</h2>
		<p class="mb-2">
			Special thanks to the prompt magicians of <a
				class="link"
				href="https://www.rpgprompts.com/"
				target="_blank">rpgprompts</a
			>, the game is run by this prompt!
		</p>
		<p class="mb-2">
			The amazing image generation is done by <a
				class="link"
				href="https://pollinations.ai/"
				target="_blank">pollinations.ai</a
			>
		</p>
		<p class="mb-2">
			The cool dice rolling feature is developed here <a
				class="link"
				href="https://github.com/3d-dice/dice-box"
				target="_blank">3d-dice dice-box</a
			>
		</p>
		<p class="mb-2">
			Favicon is created by <a class="link" href="https://icons8.com" target="_blank">icons8.com</a>
		</p>
	</section>

	<Disclaimer
		{disclaimerOpen}
		onAgree={() => {
			disclaimerOpen = false;
			goto('game/settings/ai');
		}}
	></Disclaimer>
</main>
