<script>
    import '../app.css';
</script>

<header class="bg-blue-800 p-6 text-center">
    <h1 class="text-4xl font-bold">Infinite Tales RPG</h1>
</header>

<main class="container mx-auto p-6">
    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">📜️ Shape Your Unique Tale</h2>
        <p class="mb-4">Customize every aspect of your adventure. Build your hero, explore vast lands, and make crucial decisions that determine your fate.</p>
        <p class="mb-4">Each adventure is uniquely generated by AI, ensuring that no two journeys are alike. Your choices carve out a story that is truly your own, offering endless replayability.</p>
        <ul class="list-disc pl-5 inline-block text-left">
            <li><strong>Currently in development.</strong></li>
            <li><strong>Character Stats:</strong> Define your hero's strengths and weaknesses.</li>
            <li><strong>Dice Rolls:</strong> Experience the thrill of chance and strategy.</li>
            <li><strong>Skills and Abilities:</strong> Develop unique abilities tailored to your playstyle.</li>
            <li><strong>Character Progression:</strong> Grow and evolve your character throughout the story.</li>
            <li><strong>Combat System:</strong> Engage in dynamic battles that test your tactics and wit.</li>
        </ul>
    </section>

    <section class="text-center my-8 bg-gray-800 p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-4">🎮 How to Start Playing</h2>
        <p class="mb-4">To begin your adventure, you need a Google Gemini API Key. It's free and easy to set up! Visit <a target="_blank" href="https://aistudio.google.com/" class="text-blue-400 underline">Google AI Studio</a>, generate your API key and enter the it in the game settings.</p>
        <p>Your key is securely stored in your browser, ensuring your privacy.</p>
    </section>

    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">🚀 Join the Beta</h2>
        <p class="mb-4">Experience the game in its early stages and help shape it's future.</p>
        <a href="/game/settings/ai" class="btn btn-primary">Start Playing</a>
    </section>


    <section class="text-center my-8 bg-gray-800 p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-4">🤝🏻 Contact</h2>
        <a target="_blank" class="link m-auto mt-10 flex flex-col items-center "
           href="https://github.com/JayJayBinks/infinite-tales-rpg">
            <span>Source Code & Contact at Github</span>
            <img width="25%" class="m-auto" src="https://icones.pro/wp-content/uploads/2021/06/icone-github-jaune.png"
                 alt="Github Logo"/>
        </a>
    </section>

    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">📝 Open Source</h2>
        <p class="mb-4">Infinite Tales RPG is an open-source project. Licensed under the GNU AGPLv3 License.</p>
    </section>
</main>