<script>
    import '../app.css';
    import discord from '$lib/assets/socials/discord-logo-blue.png';
    import github from '$lib/assets/socials/icone-github-jaune.png';
    import logo from '$lib/assets/logo-removebg.png';
    import Disclaimer from "$lib/components/Disclaimer.svelte";
    import {navigate} from "$lib/util.svelte.ts";

    let disclaimerOpen = $state(false);
</script>

<main class="container mx-auto p-6">
    <img src="{logo}" alt="Infinite Tales Logo"
         class="sm:w-1/4 mt-3 m-auto"/>
    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">Shape Your Unique Tale</h2>
        <p class="mb-4">Infinite Tales RPG is a Choose Your Own Adventure RPG, dynamically narrated by AI.</p>
        <p class="mb-4">Customize every aspect of your adventure. Build your hero, explore vast lands, and make crucial decisions that determine your fate. Each adventure is uniquely generated by AI, ensuring that no two journeys are alike. Your choices carve out a tale that is truly your own, offering infinite replayability.</p>
        <ul class="list-disc pl-5 inline-block text-left">
            <li><strong>Features currently in development</strong></li>
            <li><strong>Character Stats:</strong> Define your hero's strengths and weaknesses.</li>
            <li><strong>Dice Rolls:</strong> Experience the thrill of chance and strategy.</li>
            <li><strong>Skills and Abilities:</strong> Develop unique abilities tailored to your playstyle.</li>
            <li><strong>Character Progression:</strong> Grow and evolve your character throughout the story.</li>
            <li><strong>Combat System:</strong> Engage in dynamic battles that test your tactics and wit.</li>
        </ul>
    </section>

    <section class="text-center my-8 bg-gray-800 p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-4">How to Start Playing</h2>
        <p class="mb-4">To begin your tale, you need a Google Gemini API Key. It's free and easy to set up! View the <a target="_blank" href="https://github.com/JayJayBinks/infinite-tales-rpg/wiki/Create-your-free-Google-Gemini-API-Key-%F0%9F%94%91" class="text-blue-400 underline">guide to create the API Key</a></p>
        <p>Your key is only stored in your browser, ensuring your privacy.</p>
    </section>

    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">Join the Beta</h2>
        <p class="mb-4">Experience the game in the early stages and help shape it's future.</p>
        <button class="btn btn-primary" onclick="{() => disclaimerOpen = true}">Start Your Tale</button>
    </section>

    <section class="text-center my-8 bg-gray-800 p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-4">Contact</h2>
        <a target="_blank" href="https://discord.gg/CUvgRQR77y" class="link m-auto mt-10 flex flex-col items-center ">
            <span>Community Discussion at Discord</span>
            <img class="w-2/3 sm:w-1/5 mt-3 m-auto" src="{discord}" alt="Discord invite"/>
        </a>
        <a target="_blank" class="link m-auto mt-10 flex flex-col items-center "
           href="https://github.com/JayJayBinks/infinite-tales-rpg">
            <span>Source Code at Github</span>
            <img class="w-1/3 sm:w-1/12 mt-3 m-auto" src="{github}"
                 alt="Github Logo"/>
        </a>

    </section>
    <section class="text-center my-8">
        <h2 class="text-2xl font-semibold mb-4">Open Source</h2>
        <p class="mb-4">Infinite Tales RPG is an open-source project, licensed under the GNU AGPLv3 License.</p>
    </section>
    <section  class="text-center my-8 bg-gray-800 p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-2">Acknowledgements</h2>
        <p class="mb-2">Special thanks to the prompt magicians of <a class="link" href="https://www.rpgprompts.com/" target="_blank">rpgprompts</a>, the game is run by this prompt!</p>
        <p class="mb-2">The amazing image generation is done by <a class="link" href="https://pollinations.ai/" target="_blank">pollinations.ai</a></p>
        <p class="mb-2">The cool dice rolling feature is developed here <a class="link" href="https://github.com/3d-dice/dice-box" target="_blank">3d-dice dice-box</a></p>
        <p class="mb-2">Favicon is created by <a class="link" href="https://icons8.com" target="_blank">icons8.com</a></p>
    </section>

    <Disclaimer {disclaimerOpen} onAgree="{() => {disclaimerOpen = false; navigate('/settings/ai')}}"></Disclaimer>
</main>