export const storyStateForPrompt = {
    game: "Any Pen & Paper System e.g. Pathfinder, Call of Cthulhu, Star Wars, Fate Core, World of Darkness, GURPS, Mutants & Masterminds, Dungeons & Dragons",
    adventure_and_main_event: "Generate a random adventure with a random main story line. It does not have to be a quest, it can also be an event. It should be extraordinary and not cliche.",
    theme: "THEME of the story telling, e.g. world the story is located in",
    tonality: "TONALITY of the story telling, writing style, must fit GAME system",
    character: "Generate a random character fitting the GAME system in ADVENTURE_AND_MAIN_EVENT",
    general_image_prompt: "Create a general system prompt max 10 words for this adventure to add to every image that is generated by an ai. Can be art style etc.",
};

export const initialStoryState = {
    game: "",
    adventure_and_main_event: "",
    theme: "",
    tonality: "",
    character: "",
    general_image_prompt: "",
}

/**
 * storyStateForPrompt will be sent to ai to generate StoryState, overwrites can preset custom values
 */
class StoryState {
    value = $state({...initialStoryState});

    overwrites = $state({...initialStoryState});

    clear(){
        this.value = {...initialStoryState};
        this.overwrites = {...initialStoryState};
    }
}

export const storyState = new StoryState();
